spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/database/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true  # 실행중인 JPQL을 출력

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace   # SQL에 실제로 어떤값이 담겨있는지 출력
